export enum ContributorRole {
    // Artists
    PRIMARY_ARTIST = 'PRIMARY_ARTIST',
    FEATURED_ARTIST = 'FEATURED_ARTIST',
    VOCALIST = 'VOCALIST',
    BACKING_VOCALS = 'BACKING_VOCALS',
    INSTRUMENTALIST = 'INSTRUMENTALIST',

    // Writing
    SONGWRITER = 'SONGWRITER',
    COMPOSER = 'COMPOSER',
    LYRICIST = 'LYRICIST',

    // Production
    PRODUCER = 'PRODUCER',
    CO_PRODUCER = 'CO_PRODUCER',
    EXECUTIVE_PRODUCER = 'EXECUTIVE_PRODUCER',
    MIXING_ENGINEER = 'MIXING_ENGINEER',
    MASTERING_ENGINEER = 'MASTERING_ENGINEER',
    RECORDING_ENGINEER = 'RECORDING_ENGINEER',

    // Creative
    ARRANGER = 'ARRANGER',
    REMIXER = 'REMIXER',
    DJ = 'DJ',
    CONDUCTOR = 'CONDUCTOR',
    CHOIR_MASTER = 'CHOIR_MASTER',
    NARRATOR = 'NARRATOR',

    // Business
    PUBLISHER = 'PUBLISHER',
    COPYRIGHT_OWNER = 'COPYRIGHT_OWNER',
}

export enum ContributorVerificationStatus {
    PENDING = 'PENDING',
    VERIFIED = 'VERIFIED',
    NOT_VERIFIED = 'NOT_VERIFIED',
}

export enum ContributorProfileLinkType {
    WEBSITE = 'WEBSITE',
    FACEBOOK = 'FACEBOOK',
    TWITTER = 'TWITTER',
    INSTAGRAM = 'INSTAGRAM',
    YOUTUBE = 'YOUTUBE',
    SPOTIFY = 'SPOTIFY',
    APPLE_MUSIC = 'APPLE_MUSIC',
    DEEZER = 'DEEZER',
    TIDAL = 'TIDAL',
    AMAZON_MUSIC = 'AMAZON_MUSIC',
    GOOGLE_MUSIC = 'GOOGLE_MUSIC',
    SOUNDCLOUD = 'SOUNDCLOUD',
    TIKTOK = 'TIKTOK',
}

export enum ContributorType {
    INDIVIDUAL = 'INDIVIDUAL',
    GROUP = 'GROUP',
    ORCHESTRA = 'ORCHESTRA',
    CHOIR = 'CHOIR',
    OTHER = 'OTHER',
}
