// Combined Permissions Enum
export enum PERMISSIONS {
  // User permissions
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Invitation permissions
  CREATE_INVITATION = 'CREATE_INVITATION',
  READ_INVITATION = 'READ_INVITATION',
  APPROVE_INVITATION = 'APPROVE_INVITATION',
  REVOKE_INVITATION = 'REVOKE_INVITATION',

  // Role permissions
  CREATE_ROLE = 'CREATE_ROLE',
  READ_ROLE = 'READ_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  // Release permissions
  CREATE_RELEASE = 'CREATE_RELEASE',
  READ_RELEASE = 'READ_RELEASE',
  UPDATE_RELEASE = 'UPDATE_RELEASE',
  DELETE_RELEASE = 'DELETE_RELEASE',
  REVIEW_RELEASE = 'REVIEW_RELEASE',
  APPROVE_RELEASE = 'APPROVE_RELEASE',
  REJECT_RELEASE = 'REJECT_RELEASE',

  // Store permissions
  READ_STORE = 'READ_STORE',
  UPDATE_STORE = 'UPDATE_STORE',
  ASSIGN_RELEASE_STORE = 'ASSIGN_RELEASE_STORE',

  // Genre permissions
  CREATE_GENRE = 'CREATE_GENRE',
  READ_GENRE = 'READ_GENRE',
  UPDATE_GENRE = 'UPDATE_GENRE',
  DELETE_GENRE = 'DELETE_GENRE',

  // Contributor permissions
  CREATE_CONTRIBUTOR = 'CREATE_CONTRIBUTOR',
  READ_CONTRIBUTOR = 'READ_CONTRIBUTOR',
  UPDATE_CONTRIBUTOR = 'UPDATE_CONTRIBUTOR',
  DELETE_CONTRIBUTOR = 'DELETE_CONTRIBUTOR',
  VERIFY_CONTRIBUTOR = 'VERIFY_CONTRIBUTOR',

  // Track permissions
  CREATE_TRACK = 'CREATE_TRACK',
  READ_TRACK = 'READ_TRACK',
  UPDATE_TRACK = 'UPDATE_TRACK',
  DELETE_TRACK = 'DELETE_TRACK',

  // Lyrics permissions
  CREATE_LYRICS = 'CREATE_LYRICS',
  READ_LYRICS = 'READ_LYRICS',
  UPDATE_LYRICS = 'UPDATE_LYRICS',
  DELETE_LYRICS = 'DELETE_LYRICS',
  SYNC_LYRICS = 'SYNC_LYRICS',

  // DDEX permissions
  GENERATE_DDEX = 'GENERATE_DDEX',
}
