export const RELEASE_STATIC_NAVIGATION_STEPS = [
    {
        tabName: 'OVERVIEW',
        tabDescription: 'Overview',
        tabOrder: 1,
        stepName: 'OVERVIEW',
        stepDescription: 'Overview',
        stepOrder: 1,
    },
    {
        tabName: 'TRACKS',
        tabDescription: 'Tracks',
        tabOrder: 2,
        stepName: 'UPLOAD_TRACKS',
        stepDescription: 'Upload Tracks',
        stepOrder: 1,
    },
    {
        tabName: 'OVERVIEW',
        tabDescription: 'Overview',
        tabOrder: 1,
        stepName: 'MANAGE_CONTRIBUTIONS',
        stepDescription: 'Manage Contributions',
        stepOrder: 2,
    },
    {
        tabName: 'AVAILABILITY',
        tabDescription: 'Availability',
        tabOrder: 3,
        stepName: 'REGIONS',
        stepDescription: 'Regions',
        stepOrder: 1,
    },
    {
        tabName: 'AVAILABILITY',
        tabDescription: 'Availability',
        tabOrder: 3,
        stepName: 'STORES',
        stepDescription: 'Stores',
        stepOrder: 2,
    },
    {
        tabName: 'PREVIEW',
        tabDescription: 'Preview',
        tabOrder: 4,
        stepName: 'PREVIEW',
        stepDescription: 'Preview',
        stepOrder: 1,
    },
];